# Site Settings
name: Maverick Stoklosa
title: Maverick Stoklosa
email: consolemaverick@gmail.com
author: Maverick Stoklosa
description: Ansible, Command Line, Devops
tags:
  - ansible
  - console
  - linux
  - shell
  - stoklosa
  - maverick
disqus_username: maverick9000-github-io
show_hero: true
menu:
  - title: Home
    url: /
  - title: Subscribe
    url: /subscribe
  - title: Contact
    url: /contact
  - title: Open Source
    url: /code
  - title: Feed
    url: /feed.xml

external_menu:
  - title: Book
    url: https://www.amazon.com/dp/B08PDSXW6J/ref=sr_1_1?dchild=1&keywords=ansible+maverick&qid=1606879946&sr=8-1
  - title: Youtube
    url: https://www.youtube.com/channel/UCD69b3wfgT6-HMrIP4tXv_w
  - title: 哔哩哔哩bilibili
    url: https://space.bilibili.com/591877275
  - title: Presentations
    url: https://speakerdeck.com/maverick9000
  - title: Ansible Course
    url: https://www.udemy.com/course/ansible-master-course/

# Social Media Settings
# Remove the item if you don't need it
github_username: maverick9000
twitter_username: maverick5000
linkedin_username: maverick-stoklosa


# Posts Settings
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: true


# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://maverick9000.github.io" # the base hostname & protocol for your site
google_analytics: "UA-162126502-1"
language: "en"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: false
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# Theme
version: v3.0.2
